{% set name = "lagrange-ng" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/computations/lagrange-ng/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 05fac7d03e5a80e8848744247ddbdcaf0caa8ab4a25c17bef0cefef543cd3574

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - openblas
    - nlopt
    - gtest
  host:
    - openblas
    - nlopt
  run:
    - libopenblas

test:
  requires:
    - compiler-rt
    - gtest
  source_files:
    - tests/conda/conda-test.conf
    - tests/conda/conda-test.nwk
    - tests/conda/conda-test.phy

about:
  home: https://github.com/computations/lagrange-ng
  summary: 'A tool for computing ancestral range distributions under the DEC model'
  description: |
    The new version of Lagrange, a tool to infer ancestral ranges and splits
    using the DEC model. For a detailed explanation of the please see our
    publication in Systematic Biology.
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE
  doc_url: https://github.com/computations/lagrange-ng
  dev_url: https://github.com/computations/lagrange-ng

extra:
  recipe-maintainers:
    - computations
